In [1]:
import numpy as np

In [2]:
x=np.array([1,3,5])

In [3]:
x.mean

<function ndarray.mean>

In [4]:
x.mean()

3.0

In [5]:
y=np.array([1,5,9])

In [6]:
y.mean()

5.0

In [7]:
x.shape

(3,)

In [8]:
y.shape

(3,)

In [1]:
import math

In [2]:
math.pi

3.141592653589793

In [4]:
math.cos(math.pi/2)

6.123233995736766e-17

In [5]:
np.sqrt([1,5,9])

NameError: name 'np' is not defined

In [6]:
import numpy as np
np.sqrt([1,5,9])

array([ 1.        ,  2.23606798,  3.        ])

In [7]:
_

array([ 1.        ,  2.23606798,  3.        ])

In [8]:
_ * 2.3

array([ 2.3       ,  5.14295635,  6.9       ])

In [9]:
_ ** 2.5

array([   8.02268222,   59.9835404 ,  125.06123896])

In [21]:
import random
random.choice([1,5,24,55,66])

1

In [35]:
random.choice(['ali',35,37,45,55,'meesam',"",[1,3,5]])

[1, 3, 5]

In [24]:
_

37

In [36]:
Type(False)

NameError: name 'Type' is not defined

In [37]:
type(False)

bool

In [38]:
True and not False is True

True