## Re-review of Numpy Library

In [1]:
import numpy as np
import math
a = np.array([1, 2, 3])
print(a.ndim)

1


In [2]:
b = np.array([[1,2,3], [4,5,6]])

In [3]:
b.shape

(2, 3)

In [4]:
np.random.rand(2,3)

array([[0.8508927 , 0.5915948 , 0.31807481],
       [0.59184092, 0.73264799, 0.46502088]])

In [5]:
f = np.arange(10, 50, 2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [6]:
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [14]:
np.random.randint(1, 10)

8

In [17]:
array = np.array([np.random.randint(0.1, 1) * 255, np.random.randint(0, 1) * 255])
mask = np.full(array.shape, 255)
mask

array([255, 255])

In [18]:
modified = array - mask
modified *= -1
modified = modified.astype(np.uint8)
modified

array([255, 255], dtype=uint8)